# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_bank', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_bank.Bank'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blood_bank.Bank'),
        ),
    ]
